2023-01-18 14:14:52,755 ERROR: Exception on /edit_profile [POST] [in /home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py:1742]
Traceback (most recent call last):
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/pi/Desktop/math_website/app/routes.py", line 249, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3444, in flush
    self._flush(objects)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3584, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3544, in _flush
    flush_context.execute()
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 633, in execute
    uow,
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 242, in save_obj
    update,
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1002, in _emit_update_statements
    statement, multiparams, execution_options=execution_options
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('elise', 'I am the teacher this term.', 2)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2023-01-19 07:14:53,780 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-19 07:16:25,183 ERROR: Exception on /edit_profile [GET] [in /home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py:1742]
Traceback (most recent call last):
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/pi/Desktop/math_website/app/routes.py", line 245, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/pi/Desktop/math_website/venv/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/pi/Desktop/math_website/app/forms.py", line 63, in __init__
    super(EditProfile, self).__init__(*args, **kwargs)
NameError: name 'EditProfile' is not defined
2023-01-19 07:17:55,281 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-19 07:25:39,222 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-22 08:01:05,684 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-22 08:01:29,423 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-23 15:24:03,037 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-23 15:43:34,167 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-24 08:20:10,518 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-24 08:20:53,092 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-24 08:21:28,097 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-24 08:25:41,803 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-24 08:52:48,905 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-01-26 08:40:34,198 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-01 14:43:21,715 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-04 15:51:24,583 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-05 15:50:39,130 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-06 15:09:39,347 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-11 14:21:03,659 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-12 11:10:37,135 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-13 16:08:26,301 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-16 07:58:16,731 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-17 14:59:26,355 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-17 14:59:53,397 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
2023-02-18 12:28:30,184 INFO: Math Website startup [in /home/pi/Desktop/math_website/app/__init__.py:58]
